// <auto-generated />
using System;
using ApiService.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiService.Migrations
{
    [DbContext(typeof(DatabaseContextApi))]
    [Migration("20251230145052_AddExternalNummer")]
    partial class AddExternalNummer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiService.Models.Begroting", b =>
                {
                    b.Property<int>("Jaar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Jaar"));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Totaalbedrag")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Jaar");

                    b.ToTable("Begrotingen");
                });

            modelBuilder.Entity("ApiService.Models.Begrotingsregel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BegrotingJaar")
                        .HasColumnType("int");

                    b.Property<string>("KostenplaatsCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Kostensoort")
                        .HasColumnType("int");

                    b.Property<int?>("MedewerkerNummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BegrotingJaar");

                    b.HasIndex("KostenplaatsCode");

                    b.HasIndex("MedewerkerNummer");

                    b.ToTable("Begrotingsregels");
                });

            modelBuilder.Entity("ApiService.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Crediteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MedewerkerNummer")
                        .HasColumnType("int");

                    b.Property<string>("OrganisatorischeEenheidCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Rekening")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedewerkerNummer");

                    b.HasIndex("OrganisatorischeEenheidCode");

                    b.ToTable("Contracten");
                });

            modelBuilder.Entity("ApiService.Models.Dienstverband", b =>
                {
                    b.Property<int>("Nummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nummer"));

                    b.Property<int?>("Ancienniteit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumInDienst")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumUitDienst")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExternalNummer")
                        .HasColumnType("int");

                    b.Property<string>("Functiecode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MedewerkerNummer")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nummer");

                    b.HasIndex("Functiecode");

                    b.HasIndex("MedewerkerNummer")
                        .IsUnique();

                    b.ToTable("Dienstverbanden");
                });

            modelBuilder.Entity("ApiService.Models.Functie", b =>
                {
                    b.Property<string>("Functiecode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Functienaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schaall")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Functiecode");

                    b.ToTable("Functies");
                });

            modelBuilder.Entity("ApiService.Models.Inhuurkosten", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KostenplaatsCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PeriodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KostenplaatsCode");

                    b.HasIndex("PeriodeId");

                    b.ToTable("Inhuurkosten");
                });

            modelBuilder.Entity("ApiService.Models.Kostenplaats", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganisatorischeEenheidCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Code");

                    b.HasIndex("OrganisatorischeEenheidCode");

                    b.ToTable("Kostenplaatsen");
                });

            modelBuilder.Entity("ApiService.Models.Medewerker", b =>
                {
                    b.Property<int>("Nummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nummer"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExternalNummer")
                        .HasColumnType("int");

                    b.HasKey("Nummer");

                    b.ToTable("Medewerkers");
                });

            modelBuilder.Entity("ApiService.Models.OrganisatorischeEenheid", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Code");

                    b.HasIndex("ParentCode");

                    b.ToTable("OrganisatorischeEenheden");
                });

            modelBuilder.Entity("ApiService.Models.Periode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Jaar")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Maand")
                        .HasColumnType("int");

                    b.Property<bool>("Verwerking")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Periodes");
                });

            modelBuilder.Entity("ApiService.Models.Transactie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Transacties");
                });

            modelBuilder.Entity("ApiService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApiService.Models.Begrotingsregel", b =>
                {
                    b.HasOne("ApiService.Models.Begroting", "Begroting")
                        .WithMany("Begrotingsregels")
                        .HasForeignKey("BegrotingJaar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiService.Models.Kostenplaats", "Kostenplaats")
                        .WithMany("Begrotingsregels")
                        .HasForeignKey("KostenplaatsCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiService.Models.Medewerker", "Medewerker")
                        .WithMany("Begrotingsregels")
                        .HasForeignKey("MedewerkerNummer")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Begroting");

                    b.Navigation("Kostenplaats");

                    b.Navigation("Medewerker");
                });

            modelBuilder.Entity("ApiService.Models.Contract", b =>
                {
                    b.HasOne("ApiService.Models.Medewerker", "Medewerker")
                        .WithMany("Contracten")
                        .HasForeignKey("MedewerkerNummer")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiService.Models.OrganisatorischeEenheid", "OrganisatorischeEenheid")
                        .WithMany("Contracten")
                        .HasForeignKey("OrganisatorischeEenheidCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Medewerker");

                    b.Navigation("OrganisatorischeEenheid");
                });

            modelBuilder.Entity("ApiService.Models.Dienstverband", b =>
                {
                    b.HasOne("ApiService.Models.Functie", "Functie")
                        .WithMany("Dienstverbanden")
                        .HasForeignKey("Functiecode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiService.Models.Medewerker", "Medewerker")
                        .WithOne("Dienstverband")
                        .HasForeignKey("ApiService.Models.Dienstverband", "MedewerkerNummer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Functie");

                    b.Navigation("Medewerker");
                });

            modelBuilder.Entity("ApiService.Models.Inhuurkosten", b =>
                {
                    b.HasOne("ApiService.Models.Kostenplaats", "Kostenplaats")
                        .WithMany("Inhuurkosten")
                        .HasForeignKey("KostenplaatsCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiService.Models.Periode", "Periode")
                        .WithMany("Inhuurkosten")
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kostenplaats");

                    b.Navigation("Periode");
                });

            modelBuilder.Entity("ApiService.Models.Kostenplaats", b =>
                {
                    b.HasOne("ApiService.Models.OrganisatorischeEenheid", "OrganisatorischeEenheid")
                        .WithMany("Kostenplaatsen")
                        .HasForeignKey("OrganisatorischeEenheidCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganisatorischeEenheid");
                });

            modelBuilder.Entity("ApiService.Models.OrganisatorischeEenheid", b =>
                {
                    b.HasOne("ApiService.Models.OrganisatorischeEenheid", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ApiService.Models.Transactie", b =>
                {
                    b.HasOne("ApiService.Models.Contract", "Contract")
                        .WithMany("Transacties")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("ApiService.Models.Begroting", b =>
                {
                    b.Navigation("Begrotingsregels");
                });

            modelBuilder.Entity("ApiService.Models.Contract", b =>
                {
                    b.Navigation("Transacties");
                });

            modelBuilder.Entity("ApiService.Models.Functie", b =>
                {
                    b.Navigation("Dienstverbanden");
                });

            modelBuilder.Entity("ApiService.Models.Kostenplaats", b =>
                {
                    b.Navigation("Begrotingsregels");

                    b.Navigation("Inhuurkosten");
                });

            modelBuilder.Entity("ApiService.Models.Medewerker", b =>
                {
                    b.Navigation("Begrotingsregels");

                    b.Navigation("Contracten");

                    b.Navigation("Dienstverband");
                });

            modelBuilder.Entity("ApiService.Models.OrganisatorischeEenheid", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Contracten");

                    b.Navigation("Kostenplaatsen");
                });

            modelBuilder.Entity("ApiService.Models.Periode", b =>
                {
                    b.Navigation("Inhuurkosten");
                });
#pragma warning restore 612, 618
        }
    }
}
